// Parole del Wordle (solo italiano, 5 lettere, senza accenti).
// SOLO lato server: la parola della settimana non deve mai arrivare al browser.

// Possibili parole segrete: scelte a mano, nomi e aggettivi comuni.
// 329 parole = più di 6 anni di settimane senza ripetizioni.
export const SOLUZIONI: string[] = (
  "acqua aereo agile amaro amica amico anima animo arena aroma asino astro " +
  "atomo aureo avena bacio baffo bagno banca banco barba barca basso bello " +
  "bimbo birra bocca bolla borsa bosco botte bravo brodo bruco buono burro " +
  "busta calce caldo calma campo canna canoa canto cappa capra carro carta " +
  "casco cassa causa cella cento cervo cesto cielo cigno cinta circo clima " +
  "cobra colla colle colpo conto coppa corda corno corpo corsa corte costa " +
  "cotta cozza crema crepa croce cuoco cuore curva danza dente dieta disco " +
  "dolce donna drago duomo ebano esame fango farro fauna felce ferro festa " +
  "fetta fiaba fieno fiore fiume flora folla fondo fonte forno forte forza " +
  "frate freno fungo fuoco gallo gamba gatto gazza gemma genio gesso ghiro " +
  "giada gilet gioco gioia gnomo gomma gonna grano grido guado icona idolo " +
  "igloo isola koala lacca ladro lampo largo lasso latte legno lente leone " +
  "lepre letto liana libro lince linea lotta lotto lungo luogo madre magia " +
  "mamma mango manto mappa marea mazzo mente mento merlo metro miele mille " +
  "mirto molla mondo monte morso mosca motto mucca museo nonna nonno norma " +
  "notte nuoto oliva ombra opera orata ovile pacco padre paese palco palla " +
  "palma panca panda panna panno parco passo pasta patto paura pausa pelle " +
  "penna perla pesca pesce piano piede pigna pigro pinna pinza pista piuma " +
  "pizza poeta pollo polpo polso ponte porta porto posta pozzo prato prova " +
  "pugno punto quota radio ragno rampa regno rombo rospo rosso rullo ruota " +
  "sacco salsa salto sasso scala scena scopa scudo sedia segno selva senso " +
  "serra sfera sidro siepe sogno solco soldo sonno sorte sosta spada spago " +
  "spiga spina sport stile stufa suono tacco talco talpa tappo tarlo tasca " +
  "tasto tazza tempo tenda terra testa tetto tigre tondo tonno torre torso " +
  "torta tosse trama trave treno trono trota tuffo tuono turno uliva umore " +
  "uscio vacca valle vasca vello vento verde verme vespa veste vetro viale " +
  "video vigna villa viola volpe volto vuoto zaino zampa zanna zebra zecca " +
  "zinco zolfo zolla zucca zuppa "
)
  .trim()
  .split(" ");

// Tentativi ammessi: tutte le parole di 5 lettere del pacchetto
// "an-array-of-italian-words" (licenza MIT, github.com/hexapode/an-array-of-italian-words)
// più le soluzioni. La lista è un po' "sporca" (parole accentate troncate,
// qualche parola senza la prima lettera): per i tentativi va bene così,
// serve solo a impedire di scrivere lettere a caso tipo "aeiou".
export const AMMESSE: Set<string> = new Set(
  (
    "aaaaa aaaah aakon aalon aalox aanse aante aazar abana abani abara abate " +
    "abato abbar abbia abbie abbit abbra abbri abeel abele abelo abero abete " +
    "abeti abeul abeus abhat abian abien abier abies abila abile abili abina " +
    "abine abino abita abiti abito abits abitu abius abiya ablab ablet ablon " +
    "ablus aboni aboto abour about abrio abriq abris abriz abrus abuel abula " +
    "abusa abusi abuso acace acaco acana acari acato accal acche acchi accia " +
    "accio accis accor accus acere acero acete aceto aceva acevo achar achea " +
    "acher achid acida acide acidi acido acile acili acing acini acino aciti " +
    "acito ackal acked acker acket ackie acobs acola acolt acoma acone acopo " +
    "acovo acqua acque acqui actic actor actus acume acuso acust acuta acute " +
    "acuti acuto adaab adama adame adana adani adano adate adaya adden adder " +
    "addii addio addle addoo adelt adena adeon adera adere adges adget adhai " +
    "adhwa adial adian adice adici adico adies adieu adini adino adipe adise " +
    "adito admin adoan adoff adoin adola adono adora adori adoro adott adova " +
    "adrac adres adrid adron adrul adsen adult aduta aduti aduto adweg adzam " +
    "aedra aeger aella aenza aerea aeree aerei aereo aesar aesta aetta afael " +
    "afano afare afari afeet afele afety affar affei affer affid affin afona " +
    "afoni afosi afoso afran aftar after afuni again agami agani agano agari " +
    "agata agath agati agave agavi agavo agdad agels agent aggar agger aggia " +
    "aggie aggio aggir aggis agica agico agile agili agina agine aging agino " +
    "agion agire agita agite agito agiva agles aglia aglio agnai agnar agner " +
    "agnet agnos agnum agnus agona agone agoon agore agori agots agrin agris " +
    "agroa aguar aguna agusa aguto ahaha ahama ahara ahbat ahbub ahead aheed " +
    "ahhhh ahill ahime ahimi ahiti ahles ahlia ahlil ahman aholo ahora ahren " +
    "ahrez ahrir ahuna ahweh aiale aiamo aiano aibow aicie aicol aicon aidan " +
    "aiden aider aidue aight aikin ailer ailey ailla ailly ailor aiman aimie " +
    "ainan ainer aines ainte aints aiolo aione aiori airag airne airro aisal " +
    "aiser aisha aison aitta aiuno aiuta aiuti aiuto aiver aiwan aizen aizza " +
    "ajada ajana ajeed ajesh ajita ajoli ajont akami akano akati akeka akers " +
    "akery aking akita akkox aklad akley akopi akota akshi aksim aksud akula " +
    "akura akuro alaam alabi alabr alace aladi alaga alagi alais alaka alala " +
    "alali alame alamo alani alano alapa alard alare alary alass alata alate " +
    "alati alato alawi alaxy alazo alboa album alcea alchi alcio alcol alcom " +
    "alcon alcun alder aldil aldir aleae alegr alema alemi alena aleno alent " +
    "aleri alero alert alery alghe alham alias alibi alici alick alico alida " +
    "alide aliel alige align alika alimi alina aline alini alino alire alita " +
    "alite alito alium aliva alkan alker alkie allad allai allaj allar allas " +
    "allea allen alleo alles allet alley allia allio allir allis allle allon " +
    "allow allum allup alman almas almer alois aloma alona alone aloni alopy " +
    "alora alore alori aloud alper alpha alpiu alque alser alsey altea alter " +
    "alton altra altre altri altro aluni aluso aluta alute aluti aluto alvar " +
    "alveo alvia alzac alzai alzer alzoe amaca amada amadi amady amage amaha " +
    "amako amalo amana amano amara amare amari amaro amata amate amati amato " +
    "amava amavi amavo ambia ambin ambio amble ambon ambor ambow ambra amden " +
    "ameba amebe amecc ameem amela ameli amena ameno amera amere ameti amica " +
    "amici amico amida amidi amido amien amigi amija amila amily amina amine " +
    "amino amion amira amito ammal ammer ammes ammin ammon ammut amned amoli " +
    "amone amont amore amori amoru amosi amoso amour amous ampax ampei ampff " +
    "ampia ampie ampio ampis ampli ampon ampti ampur ampus amsay amses amsey " +
    "amsun amuel anaan anach anada anage anaka anald anale anali anama aname " +
    "anana anang anara anard anaro anban anbij anbji ancat ancer ancet ancey " +
    "ancge ancha anche anchi ancho ancia ancic ancii ancio ancor ancri ancro " +
    "andai andar andas andau andeg andel ander andhi andia andid andit andji " +
    "andon andor andra andre andri andro aneke anela aneli anelo anese anete " +
    "angar angea angel anger anghe anghi angia angio angla anglo angon angor " +
    "angos angry angue anica anice anico aniel anier anigo anila anilo anima " +
    "anime animi animo anine anini anino anish anita anity anjan ankaa anksy " +
    "ankyo anlic anlio anlle anmen annah anndi annen anner annes annia annie " +
    "annik annis annoi annot annua annui annuo annus anoel anois anolo anomi " +
    "anone anoni anora anosa anosz anova anovi ansas ansel ansen ansey ansia " +
    "ansie ansky anson antan antar anted anter antes antis anton antor antos " +
    "antra antri antro anuel anuso anuta anvas anyon anzai anzer anzio aobab " +
    "aodel aorle aoudi apace apaci apale apalm apato apera apere aperi apero " +
    "apers apete apeva apevi apevo aphod apice apici apido apier apina apini " +
    "apire apiro apita apite apito apivo apley apnea apoel apoli apore apori " +
    "appas apper apple apply aprai aprie aprii aprio aprir aprte apsus aptia " +
    "aptor aptus apura aputi aputo aqdis aques aquet araba arabe arabi arabo " +
    "araci arack arade arage arald arale aranh arani arano arare arata arati " +
    "arato araya arber arbie arbon arbra arbus arcel arche archi arcia arcor " +
    "arcos arcus arden arder ardex ardim ardin ardio ardua ardue ardui arduo " +
    "aredo areee arega areha aremo arena arene arent arese aresi arete areto " +
    "arfur argan argas argen arger arges arget argin argis argli argot arhad " +
    "arhan arhol arhus ariam arian arias arica arice arida aride aridi arido " +
    "aries ariet arifa arigi arija arika arina arine aring arini arino arisa " +
    "arisi ariti arito arius arjev arkar arker arket arkup arkus arlan arlem " +
    "arler arley arlin arlon arlos arlov arlow arman armen armer armes armin " +
    "armon armor armot arner arney arnia arnie arnum arodi arody arola arold " +
    "arole arolo aroma aromi arone aroni arono arook aroon arose arosi arouk " +
    "arouq arper arpet arpez arpie arque arraj arral arram arras array arrel " +
    "arren arrer arres arret arrey arrie arrio arris arriv arrix arrod arrol " +
    "arron arros arrot arrow arroz arryd arryl arsen arski arson arsus arted " +
    "artei artel artem arten arter artha arthe arths arthy artic artin artir " +
    "arton artre aruff arufi arugo aruki aruso arvel arven arver arvey arvin " +
    "arvis arwin aryan arzan arzia arzio asabi asaje asaka asaki asale asali " +
    "asana asane asani asano asari asata asati asato asava asbah asbro ascal " +
    "ascer ascha aschi ascia ascio asdaq aseio asera aseus ashal ashar asher " +
    "ashid ashif ashin ashup asich asick asija asile asili asilo asina asing " +
    "asini asino asito asjid asket aslow asohl asoio asola asole asolo asoni " +
    "aspar aspei asper aspir aspra aspre aspri aspro asqua assad assai assan " +
    "assar assau assei asser asset assey assia assie assim assin assis assiu " +
    "assoc asson assos assry astel aster astia astio astle aston astor astri " +
    "astro asuda async aszlo atale atali ataly atana atani atano atari atarn " +
    "atato atboy atcha ateau ateci ateen atelo ateme atemi atena atene atent " +
    "atera aters atese atevi athan ather atica atico atija atima atina ating " +
    "atini atino ation atira atiri atiro ative ativo atman atmut atnaj atney " +
    "atoki atolo atomi atomo atona atone atore atori atort atoru atque atria " +
    "atrio atrix atriz atrol atron atsby atson attah attai attea attei attel " +
    "atten atteo atter attia attir attis attle attoi atton attor attra attua " +
    "atuma atura ature aturi aturn auban aucco aucus audio audit auini aulin " +
    "aulle aulto auman aunas aunch auncz aurea auren aureo auriz aurus auryl " +
    "ausch auses austi austo autem autes autor autre auzzi avabo avage avala " +
    "avale avani avans avant avanz avara avare avari avaro avemo avena avere " +
    "averi avern avero avert avese aveta avete aveva avevi avevo avico avida " +
    "avide avidi avido avier avies avigo avile avill avina avino avlov avoca " +
    "avoia avola avole avoli avolo avona avone avoni avora avori avoro avour " +
    "avrai avrei avron avrov avteq avuta avute avuti avuto avvia avvii avvin " +
    "avvio awaii award aware awhid awlor awson awton axaca axalt aximo ayadh " +
    "ayane ayard ayata ayato ayden ayeri ayern ayers ayhan ayhem aykin ayley " +
    "aylor ayman aynee ayout aypal aysen ayton ayyeb ayyib ayyip azaar azara " +
    "azbek azebo azera azidi azien azila azima azira azoto azslo azuki azuyo " +
    "azzei azzeo babbi babbo bacca bacer bacia bacio bacon badar bader badge " +
    "baffi baffo bagli bagna bagni bagno baita baite baker baldi baldo balen " +
    "balia balla balle balli ballo balsa balza balzi balzo banca banco banda " +
    "bande bandi bando bands banjo banks banku bantu baori barba barbe barca " +
    "barco bardo barje barra barre basai basca basco based basic bassa basse " +
    "bassi basso basta basti basto batch bateo batik batte batti batto baule " +
    "bauli bazar bbaco bbate bbene bbott bbuon bdico beach beata beati beato " +
    "beats becca becco beffa beffe beghe begli beige belga belgi belix bella " +
    "belle belli bello bells belva belve bembe bench benda bende benjo benna " +
    "bensi beota beppe beran berci beree beria berla berlo bermi berne bersi " +
    "besit betty bevve biada biamo bianc biano biata bidet bieca bieco bigoi " +
    "bilit bimba bimbe bimbi bimbo binge bingo birci birra birre bisce bisex " +
    "bissi bisso bistr bitch bites bitov bivio bject black blema blemi blend " +
    "bleus blica blico bling blitz blocc block blues bluff blunt blusa blush " +
    "board boato bocca bocce bocci boema boemo bokeh bolla bolle bolli bollo " +
    "bolon bomba bombe bombo bonus bonzo books bordi bordo borgo boria borsa " +
    "borse borto bosco botox botta botte botti botto boule bowee boxed boxer " +
    "bozza bozze brace braci brado braha brain brama brame brami bramo brams " +
    "brand brani brano brare brasa brava brave bravi bravo bread break brede " +
    "breve brevi brick bridi brief briga brina broad broda brodi brodo bruci " +
    "bruco bruma bruna brune bruni bruno brush bruta brute bruti bruto bside " +
    "btato bubbo bucan bucce buche buchi buddy budge buffa buffe buffi buffo " +
    "bugia bugie build built bulbi bulbo bulli bullo bunga buntu buona buone " +
    "buoni buono burbe burer burka burla burri burro bussa bussi busso busta " +
    "buste busti busto butta butti butto buyer bydos cable cacao cacca cacce " +
    "cacci cache cachi cacio cadde cadra caete caffe cagli cagna cagne cahet " +
    "calar calca calce calci calda calde caldi caldo caler calia calle calli " +
    "calma calme calmi calmo calvi calvo calza calze cambi camel cameo campa " +
    "campi campo canap canea canna canne canno canoa canoe canta canti canto " +
    "canza canzi caoda caoti capia capii capir capit cappa cappo capra capre " +
    "capri capro capta carde cardo cards cargo carib caric carie carit carne " +
    "carni carny carpa carpe carri carro carsi carta carte carus casas casca " +
    "casco casei casin cassa casse casta caste casto casus cativ catta catti " +
    "catto cauda causa cause cauta caute cauti cauto cavar cavie cavit caxxo " +
    "cazzi cazzo cbert ccade ccadr ccedi ccesa ccese ccess cchei cchio cchiu " +
    "ccidi ccisa ccise ccisi cciso ccoci ccola ccole ccoli ccolo ccome ccomi " +
    "ccone ccoti ccovi ccupa ccupy ccuse cdnit ceage ceano cebug cechi cecit " +
    "ceder cedri cedro cefal ceffi ceffo cegli celba celeb celer celgo cella " +
    "celle celsi celta celte celti celto cenao cende cendi cendo cenni cenno " +
    "censo cente cento cents ceppi ceppo cerbo cerca cerco ceres certa certe " +
    "certi certo cervi cervo cesio cessa cessi cesso cesta ceste cesti cesto " +
    "cette chael chain chans chaos chart chayn chdei cheap check cheda chedi " +
    "chefs chele chema chemi chese chesi chess cheta chiam chiap chiby chick " +
    "chico chidu chief chiei chien chiff chifo child chili chilo china chine " +
    "chini chino chios chipa chips chiss chiva cholo chomp chool chste chula " +
    "chulz chuso chutz chviz chwab ciano ciati cibus cicca ciccu cicli ciclo " +
    "cieca cieco cieli cielo cienz ciesa cifra cifre cigli cigni cigno ciiti " +
    "cilea cilio cilla cilum cimae cinge cinse cinta cinti ciofs cipia cippa " +
    "cippo circa circo cirip cisti cisto citai citer citta civic civil civit " +
    "claim clair clame class clava clavi clean clero cleup clich click clima " +
    "climi clips clito clock clohe clona clone cloni cloro close cloud clown " +
    "cmesa coach cobra cocci cocco codaa codec coeli coesa coese coesi coeso " +
    "coeva coevi cofee coffe cofin coggi cogli coisp coito colei colga colgo " +
    "colla colle colli collo colma colme colmi colmo colon color colpa colpe " +
    "colpi colpo colse colta colte colti colto colui colza comau combo comel " +
    "comic comit comix comma comme commi compa compi compo compr comte comun " +
    "conca conci conda condi condo conia conil conio conla consi conso conta " +
    "conte conti conto cooby cooso copia copie copio coppa coppe coppi copra " +
    "copre copri copro copta copul coram coraz corci corda corde coreo corgo " +
    "corna corni corno corpi corpo corra corre corri corro corsa corse corsi " +
    "corso corta corte corti corto corvi corvo corza cosca cosce cosmo cossa " +
    "cosso costa coste costi costo cotos cotta cotte cotti cotto cottu couch " +
    "could count court couts cover cozia cozza cozze cquel crack craft crash " +
    "craxi crazy cream creat creda crede credi credo creen creer crema creme " +
    "crepa crepe crepi crepo creta criba cribd crica crick crime crine cript " +
    "crisi crisp crive crivi crivo croce croci crock croll cromo crono cross " +
    "crowd cruda crude crudi crudo crunk cruto ctemi ction ctiva ctive cucco " +
    "cuccu cucin cuiil culla culle cully culpa culti culto culus cumpa cuneo " +
    "cunti cuoca cuoce cuoco cuoia cuoio cuola cuole cuore cuori cuote cuoto " +
    "cupio curai curda curde curdi curdo curer curia curre curva curve curvi " +
    "curvo curvy cvise cyber cycle dabda dacca dacch dagli daily dairy dalet " +
    "dalit dalla dalle dallo dallu damme dammi dance dando dandy danna danni " +
    "danno danse danza danze danzi danzo darai daras darci dardi dardo darei " +
    "darla darle darli darlo darmi darne darsi darti darvi dashi datta datti " +
    "datto datur dazio ddams ddici ddity deale deali deare deata death debba " +
    "debbo debug dedic dedle defer defin degli degna degne degni degno dejav " +
    "delav delay delio della delle dello dellr delta delto demmo demos denek " +
    "densa dense densi denso dente denti dento deole depot depti derby derev " +
    "derlo derma dersi desid dessa desse desso desta desti deter detox detta " +
    "dette detti detto devia devon diami diamo diano diare diari diate diati " +
    "diato diava diavo dicci dichi dicom dicon didad didas dieci diede diedi " +
    "dieta diete dighe digli dilag dillo dilyn dimmi dimon dimor dindi diner " +
    "dioso diota dioti dipen dirai dirci direi dirla dirle dirlo dirmi dirne " +
    "dirsi dirti dirto dirvi disco disfa dislo dison disse dissi disso dista " +
    "ditor ditta ditte diven divor dixan djset djust dlaro dmira dmodo dmond " +
    "dmund dmure dnani dndia docce docet docno doggy dogma dogmi doing dolby " +
    "dolce dolci dolfo dolph dolse domin donar donax donde donee doner donis " +
    "donna donne doocs doors doppi dorma dorme dormi dormo dorno dorso dossi " +
    "dosso dotta dotte dotti dotto doubt dover dovra dovro draft drago drama " +
    "dream dreno dress drian drien drija drink drive droga drone droni drugs " +
    "drums drunk drupe drusa duale duali duard dubbi dubit duchi dulti duole " +
    "duomo durer dvard dvige dward eachy eacon eader eafak eagan eagle eague " +
    "ealer ealla ealms ealth eanne earch eardo earle early earth earts easho " +
    "eason eaton eatri eatro eauty eaven eaver eaves eazza ebano ebate ebbia " +
    "ebbie ebble ebbre ebbro ebete ebeti ebian ebito eboli ebook ebora ebord " +
    "ebout ebrea ebrei ebreo ebula ecadr ecaro ecati ecava ecbop eccca ecchi " +
    "ecero echat echia echov ecico ecide ecidi ecido ecife ecima ecimo ecina " +
    "ecine ecipe ecise ecisi eciso ecita ecius eckel eclam eclis ecoli ecolo " +
    "econd ecora ecord ecore ecpob ecrae ecret ecter ector ecure eczup edalo " +
    "edato eddah edder eddit edele edeli edelt edemi edera edere edese edete " +
    "edevi edevo edger edica edici edico edila edile edili edimi edina edine " +
    "edita edite edito edium edizi edoni edono edora edori edout edova edove " +
    "edrai edric educa educe educi educo eduli edull eduri edusa eduta eduti " +
    "eduto edzan eebok eedly eegan eejay eeknd eeler eeley eensi eepak eertu " +
    "eertz eesay eeson eeter eetup eezer eezus efana efeli effee effet eflav " +
    "eflix efore eform egacy egala egale egali egalo egami egana egani egano " +
    "egare egasi egaso egata egate egati egato egend egeni egete eggar egger " +
    "eggia eggie eggio egida egime egina egine egion egizi eglie eglio egnai " +
    "egner egnit egoit egola egole egozi egual eguii eguir egypt ehari ehind " +
    "ehisi ehman ehmet ehmmm ehran eiani eibel eiden eider eiger eigns eimar " +
    "eimos einab eintz eirce eirut eisha eishi eison eisti eitur ejima ejita " +
    "ejore ekeli ekhem ekkan ekken ekong ekyll elado elaia elais eland elano " +
    "elate elati elato elcom eleco elect elegy elehe eleka elena elene eleno " +
    "eleto eleva elfie elgio elica elice elici elido elief eligo elika eline " +
    "eling elini elipe elisa elise elisi elite elito elius elkoo ellal ellan " +
    "ellar ellen eller elles elley ellie ellin ellis ellon ellos ellow elmut " +
    "eloce eloci elogi eloni elope elors elosi eloso elrio elson eltic elton " +
    "eltre eltri eluar eluli elusa eluse eluso eluxe elvet elvin elzeb email " +
    "emain emale emana emand emane emani emato embed ember embra embri embro " +
    "emene emere emero emesi emeva emevo emici emico emima emina emini emiri " +
    "emise emkin emmai emoji emona emone emoni emori emory emote empel emper " +
    "empia empio emple empli empre emula emule emuli emulo enace enale enali " +
    "enang enape enard enari enaro enate enati enato enbij encha encia encil " +
    "endai endel ender endes endic endit endur eneau eneca enemy enera enerd " +
    "enere eneri enesi eneta enete eneto eneux eneva enevo enfer enfop engag " +
    "engai enger engis enice enici enier enini enior enise enite enith enito " +
    "enius eniva enjoy enley ennea enner ennes ennet ennis ennon ennui enobi " +
    "enoit enomi enone enoni enore enosa enova enpai enriz ensai ensan ensen " +
    "ensis enson ensor ental enter entia entii entio entir entis entit entra " +
    "entre entri entro entry enusi enuta enuto envee enver enzia enzie eolis " +
    "eomra eonis eonue eople eorge eoria eorie eossa eotta eotto epaci epage " +
    "epair epang epara epate epens epero ephir epica epici epico epino epite " +
    "epito epler epoca epolo epore eport eposi epost epper eppia eppur eputo " +
    "equee equio equit erada erais erald eramo erano erard erari erast erata " +
    "erate erato erawa erbia erbig ercai ercar erced erceg ercep ercer erche " +
    "erchi ercio erckx ercuk erder erede eredi erego eremi eremo eremy erena " +
    "erenc ereni ereno erere erero eresa eresi erfer ergal ergej ergen erger " +
    "ergey ergio erial erias erica erici erico eries erika ering erini erino " +
    "eriod eripa erita erite eriti erito eriva erive erivs erjan erkel erkst " +
    "erlag erley erlin ermai ermak erman ermat ermer ermes ernal ernan erner " +
    "ernet ernia ernie ernik ernon ernor ernry eroci eroes eroga eroge eroku " +
    "erola eroli erona erone eroni erosa erose erraj erran erraz errei erris " +
    "errit erron error erros errua erseo ersey ersia erson ertab erton ertov " +
    "eruda erulo eruta erval erver ervin ervir ervis erzog erzot esala esame " +
    "esami esana esani esare esari esaro esaur escal esche escue esena eseni " +
    "esert esfai eshua esich esige esign esile esili esima esimi esimo esina " +
    "esino esire esita esiti esito esjak eslie esmer esodi esodo esolo esoro " +
    "esort esose esosi esoso espan espar esper espii espir essai essat essau " +
    "essay essel esser essia essie essna essoa esson essun estai estek esten " +
    "ester estia estim eston estra estre estro esula esule esuli esult etail " +
    "etake etale etali etalo etana etara etere etern etero ethel ethod ethos " +
    "etica etici etico etimi etimo etina etjon etlix etlog etnia etnie etodi " +
    "etodo etofi etola etona etour etrie etris etrix etron etrus etter ettis " +
    "etzer eucci eulos euman euner eurol euron eutra eutri evada evade evaki " +
    "evant evare evase evasi evaso event evera evere evero evers every eveso " +
    "evete evica evice eview evilo evins evita eviti evito evoca evoli evono " +
    "evont evoto evski ewafa ewark ewind ewman ewton excel exels exico exler " +
    "exola expat exter extra exual exxar eyers eylon eymah eymar eymor eynes " +
    "eyonc eyond eysir ezdim ezier ezuan faber facce facci facet facil facti " +
    "facto facts faggi fagli faida faina faire faith falce falci falco falda " +
    "falde falla falle falli fallo falsa false falsi falso famme fammi famos " +
    "fancy fango fanin fanne fanno fanta fante fanti farai farci farei farel " +
    "farla farle farli farlo farmi farne farro farsa farsi farti farvi fasce " +
    "fasci fasti fatal fatta fatte fatti fatto fatuo fauci fauna fauno faute " +
    "favor fazza fceva feeds feisb felce felic felpa felpe femme fende feria " +
    "ferie ferir ferma ferme fermi fermo ferri ferro fervo fessa fessi fesso " +
    "festa feste fetta fette fetto feudi feudo ffare ffari ffect ffice ffici " +
    "ffida ffill ffizi fflek ffori ffset fgana fiaba fiabe fiama fiati fiato " +
    "fibia fibra fibre fiche fichi fidei fider field fiele fieno fiera fiere " +
    "fieri fiero fiesi fifty fighe fighi fight figli fildo filer files filma " +
    "filme filmo filze final finch finda finge fingi fingo finie finii finir " +
    "finis finit finqu finse finta finte finti finto fioca fioco fiond fiora " +
    "fiore fiori firco firma firme firmi firmo first fisco fisio fissa fisse " +
    "fissi fisso fitne fitta fitte fitti fitto fiume fiumi fiuta fiuto fixed " +
    "fixer fizer flags flame flare flash flati flebo flesh flilo flipo floor " +
    "flora floyd flyer fobia fobie foche focus fogge fogli fogna fogne folie " +
    "folla folle folli folta folte folti folto fonda fonde fondi fondo fonia " +
    "fonta fonte fonti fonts footy forca force forex forma forme formi formo " +
    "forms formu forni forno forse forte forti forum forza forze forzi forzo " +
    "fosca fosco fossa fosse fossi fosso foste fotta fotte fotti fotto found " +
    "fovea foyer fradi fraim frame frana frane frank franz frase frasi frate " +
    "frati fratm frdmr freak frega frego freja freme frena freni freno fresa " +
    "frese frica frico frigo frisa froci froda frode frodi front froos frost " +
    "fruga fruir fruit ftali fuffa fugga fugge fuggi fughe fugit fujot fulla " +
    "fully fulvo fumai fumar fummo fundo funga funge fungo funky funny fuoco " +
    "fuori furba furbe furbi furbo furia furie furor furti furto fusto fuzzy " +
    "gadez gaeta gaffe galee galit galla galli gallo gamba gambe gambi gambo " +
    "gamer games gamma ganci ganda ganga ganja gantt ganzo garan garba garbi " +
    "garbo garre garro garza garze garzi gatha gatta gatte gatti gatto gauss " +
    "gazio gazza gazzi gdala gechi gelsi gemba gemma gemme gency genda gende " +
    "gendo gener genia genio gente genti geode geome gergo gerlo germe germi " +
    "gesso gesta gesti gesto getta getti getto ggars ghera ghiro ghisa ghost " +
    "giaba giace giada giamo giano giant giare gicic gidii gidio gigli gigol " +
    "gilde gilet gilit gilvy ginia gioca gioco giogo gioia gioie giole giono " +
    "giore giori giova giphy girai girar girer girls gisci gitto giuda giura " +
    "giuri giuro giuso giust gizio glaia glali glass glaze glide gliel glifi " +
    "glifo glise globo gmail gnace gnara gnate gnavi gnazi gnegn gnese gnesi " +
    "gnome gnomo gnora gnoro gnosi gnuna gnuno goals gobba gobbi gobbo gocce " +
    "godoc godra goffa goffi goffo gogna going golem golfi golfo golpe gomma " +
    "gomme gonfi gonia gonna gonne gonza gonzi goool gordo gorgo gorno gosce " +
    "gosto gotha gotta gozzo grade gradi grado grafo grama grana grand grane " +
    "grani grano graph grata grate grati grato grava grave gravi great greca " +
    "greci greco green greto greve grevi grida gridi grido grifa grifo grige " +
    "grigi grija grill grime griot groan group grugn grumi grumo grund guado " +
    "guaio guale guana guano guard gueci guess guest guida guide guidi guido " +
    "guila guisa guito gulag gusci gusta gusti gusto haadi habab habon hadai " +
    "hades hadow hafie hagos hahed hahin haida haini hains haked hakir hakra " +
    "haled haler hales halia halil halom haman hamed hames hamps hance hands " +
    "hanel hange hania hanks hanna hanno haore happy harah haram harem harge " +
    "haria harif harks harli harly harma haron haser hashi haski hasma hasri " +
    "hasse hater haven hazam hazed hazen heads heard heavy hecch hecco hechi " +
    "heckm hedge hedon heers heese heikh heila heist helet hello helma helps " +
    "hemie hemon heney heory herbe herek herif herko herry hersi hertz hesis " +
    "hetis hetto hezzi hiago hiama hiami hiamo hiang hiara hiari hiaro hiave " +
    "hiavi hicca hicco hicke hicks hidda hieco hieda hiede hiedi hiedo hield " +
    "hiene hieri hiesa hiese hiesi hieti hieve hievo higno hijab hilae hiley " +
    "hilft hilip hills himan hings hinji hinks hiodi hioma hione hioni hippy " +
    "hiran hirow hirri hirst hissa hitus hiude hiudo hiusa hiuse hiusi hiuso " +
    "hlife hmitz hobby hobia hodes hodey hodia hodus hoebe hogun hoice holly " +
    "homas honda honey honor hooer hopin hopra horne horus hotel hoton hotos " +
    "houar houri house hraib hrall hrist hrome hsumi httai https httpv hubby " +
    "hucky hultz human humor humus hurch hurer hutan huthi hvale hynot hysis " +
    "hytaj hythm iable iablo iacco iacer iacta iafra iaget iaggi iagio iagra " +
    "iajes ialle ialli iallo ialog ialto iamey iamma iamme iampi ianca ianci " +
    "ianco iange iangi iango ianhe ianna ianni iansi ianta iante ianto iants " +
    "iaobo iaomi iaone iapre iapro iario iariy iasco iatec iatto iazza iazzi " +
    "iazzo ibact ibali ibano ibari ibbia ibbio ibera iberi ibero ibert ibico " +
    "ibiri iblat iblio ibola ibona ibran ibria ibson ibure ibuti ibyan icamo " +
    "icari icaso icata icche icchi iccia iccio iccol iceli icene iceno iceva " +
    "iceve icevi icevo ichel ichie ichil icila icily icini icino ickel icket " +
    "ickey ickok icnic icola icole icoli icolo icona icone icono icplz icron " +
    "ictor ictus icura icuri icuro icuta idach idane idani idati idaty idday " +
    "idden iddha iddle idela idere iders idesz idget iding idion idley idman " +
    "idney idoli idolo idori idoti iduce iduci idway ieber iecco ieces iechi " +
    "iedis iefer ieffe iegal iegel ields ieles iella iello ielte iemen iemex " +
    "iemme iempi iempo iener ienna iente ientr ienza ienzi ienzo ieran ierce " +
    "ierer ieria ierla ierra ierre ierri iervo iesce iesci iesco iesso iesta " +
    "ieste iesto ieter ietra ietre ietri ietro ietto iewer ifano ifavo ifesa " +
    "ifese iffel iffey ifica ifiso ifive ifkin ifosi ifpef iftci ifttt igala " +
    "igari igaro igata igaya igeon iggie iggio igher ighin ighly ights ighty " +
    "igili igini igiti iglia iglio igloo igmar ignal igner ignit ignor igoli " +
    "igone igoni igore igros igsaw iguan iguel iguno igura igure iguri igurt " +
    "ihael ihard ihhhh ihlaj iiace ijeka ikael ikail ikari ikers ikido iking " +
    "ikini ikkei ikkim ikmet iknil ikola ikret iktor ilali ilani ilano ilare " +
    "ilari ilary ilasi ilati ilato ilbao ilbau ilber ilded ilder ilean ileda " +
    "ilena ilent ilevi ilevo ilgen ilger ilinx ilita ilith ilito illar illel " +
    "illem iller illes illie illio illis illon ilner ilome ilone ilosa iloti " +
    "ilroy ilsen ilson ilter ilton iltra iltri iltro iltuo ilver ilvia ilvio " +
    "image imane imani imarr imase imasi imata imate imati imavo imber imbuc " +
    "imbuk imbum imbus imdef imedi imico imile imili imimi iming imini imino " +
    "imion imita imite imiti immel immer imona imone imono impar imped imple " +
    "impor impro imrod imuli imzej inaba inair inale inali inami inari inate " +
    "inato inche incin incio incol incon incos indag inder index india indic " +
    "indie indif indle indon indor indow indue inead inear ineco ineda inema " +
    "inese inesi ineta inete infee infeo infil influ infoi ingaz inger ingia " +
    "ingle ingol ingra ingua ingus ingxi inico inimi inimo inini inion inire " +
    "inisa inist inita inite initi inito inizi inked inker inkia inksy inley " +
    "innai inner inney innov inoli inona inope inora inori input inque inser " +
    "insey insky intei intel inten inter intim intiq intno inton intra intro " +
    "inuit inuna inuta inute inuti inuto invec invia invii invio invit inzia " +
    "inzio iobbe iocci iocco iochi iodio iolet iolfi iombi iombo ionda iondi " +
    "ionel ionie ionio ionni ionon iopia ioran iorgi iorio iorni iorno iossi " +
    "iotti iotto iovan ioved ipaie ipari iparo ipass ipepe ipera ipers ipete " +
    "ipeti ipeto ipica ipico ipino ipita iplex ipman ipoli ipone iposa iposo " +
    "ippel ipple ippon ipsia ipsos ipsum ipton iquel iquid iraci irada irana " +
    "irani irano irant irard irare irata irate irati irato irava iravo irbag " +
    "irbnb irbus irceo ircle ircus irect irena irene irens irese irete irgen " +
    "irgin irgit irgli iriam irian irica irich iride iridi irinn irish irjam " +
    "irkin irlsa irnam iroli irolo irolu irona irone ironi iroso iroud irpef " +
    "irque irror irsty irthh irtue irtus iruna isale isana isani isano isanu " +
    "isata isate isato isboa iscal ischi iscia iscio iscoe iscon isegn isegr " +
    "isele iseri isero isham isher ishop isica isida isifo isiko ising ision " +
    "isisi isita isite isito islam isler ismal isney isola isole isoli isolo " +
    "isore isper ispir isqus issan issau issed issen issto issue istas istat " +
    "isten ister istic istis istmo istri istro istru istry isual isura isure " +
    "itale italo italy itano itari itasi itati itaxi itaya itbit itela itelo " +
    "itemi itesh itges ithub itida ities itiga itiro itken itkin itlab itler " +
    "itlev itman itmap itoli itolo itomi itroe itsas itsui ittel itter ittle " +
    "itton itula itvin itwww iuann iudea iudei iuffr iugno iulia iulie iulio " +
    "iulli iunge iungo iunse iunta iunti iunto iuoco iurca iuris iurno iusta " +
    "iusti iusto iuter ivaio ivali ivano ivati iveca ivedi ivedo ivent ivera " +
    "ivere ivers ivete iveva ivevo ivian ivica ivici ivico ivide ividi ivile " +
    "ivili ivilt ivina ivine iving ivino ivisa ivisi iviso ivita iviti ivjak " +
    "ivoir ivola ivoli ivolo ivono ivrai ivrea ivver iwork ixels ixero ixers " +
    "izard izmag izoon izwan izzee jajic jamon janei janet jango janic janov " +
    "jarke jazzy jeans jelly jerry jihad joint jokes jolly joule jubov jumbo " +
    "junky justo kadar kajal kalum kamai kamut kanal kappa karit karma kasha " +
    "kauas kayak kberg kcman kebab kefir kepta kerin ketch khaki kiama killa " +
    "kills kippo klout kmazz knitr koala koduj kombu konte kopie krein krino " +
    "kropa ktion kudos kulio kurdi kylab kyrim labed label labor lacca lacch " +
    "lacci laces lachi lades ladra ladri ladro laere laese lager lages lagga " +
    "laggi laghi lagic lagna lagne lagno lagod laica laici laico laida laidi " +
    "laido laire laise lajmo laked lalle lampi lampo lanca lance lanci lanck " +
    "lanco landa lande landi lanes lanet langa lange lanna lanoo lanos lante " +
    "lants lanum laoui lapse lardo larga large largo laria lario larke larve " +
    "lasca lasci lasco laser lasio laska lasse lasso lassu latea latex latin " +
    "latja latko latra latta latte latti lauco laude laudi laudo laure lauti " +
    "lauto lavar laver laves lavia lavio lavni lavoj lavor lawed layer lazzi " +
    "lazzo lbani lbano lbarn lbere lberi lbero lbert lbini lbino lbula lcide " +
    "lcina lcool lcott lcova lcune lcuni ldani ldini ldous ldrin leads leaks " +
    "leale leali lealt lease least leave lebuh lecca lecci lecta leder leeps " +
    "leese legai legal legga legge leggi leggo leghe leghi legna legne legni " +
    "legno legre leist lello lembi lembo lemma lemmi lemon lenco lenel lenia " +
    "lenta lente lenti lento lenum lenza leona leone leoni leppe leppo lepre " +
    "leria lerte lerts lesbo lessa lesse lessi lesso leste lesto letta lette " +
    "letti letto levar level leven levet lexas lexey lexis lezza lfama lfano " +
    "lfero lfred lgida lheim liade liana liane liano liber libre libri libro " +
    "licca licco licei liceo lichy licia lickr licra lider lides liela liele " +
    "lieli lielo liema liena liene lieni lient liese lieta liete lieti lieto " +
    "lieve lievi ligat light ligia ligio ligny lijah likes lilla limar limbo " +
    "limes limin limit limon limpo lince linci linda lindi lindo linea linee " +
    "linfa linic linio linka linki linko linux linuz lirck lisce lisci lisei " +
    "liseo lison lisse lista liste litan litch lites litio litri litro liuti " +
    "liver lives livia lizia lizio lizzy lkann lkins lland llego llena lleno " +
    "lleri llery lleva llevi llich llida lliot llone llora lltec llume llung " +
    "lmeda lmeni lmeno lmore lnare lnore loagh loale lobal lobby local locca " +
    "locco locko locum loden loder lodge lodio lofts logan logga logge loghi " +
    "logia login logio logos lohim loisa lombi lombo londo loner longa loody " +
    "loppy lorca lorde lordi lordo loria lorio loris losco loser loses lotio " +
    "lotta lotte lotti lotto lotus lough lovak lover loves lowes lowig lpaca " +
    "lpago lpher lpina lpini lrich lrico lrike lster lstom ltair ltare ltera " +
    "ltern ltero ltima ltime ltimi ltimo ltino ltore ltras ltrep ltres ltron " +
    "ltrui luana lucky lucro luedo lugin luiad luido lumen lumia lumni lunar " +
    "lunch lundo luned lunga lungi lungo luogo lurka lusit lussi lusso lutti " +
    "lutto luxus lvaro lvena lvira lvise lways lwood lycra lying lyzer lzare " +
    "lzati lzino macch macho macro maddy madeo madre madri maest mafia mafie " +
    "mager mages maghi magia magic magie magli magma magna magno magra magre " +
    "magri magro major maker malat maldi malfi malga malge malia malta malte " +
    "malto malus mambo mamey mamma mamme manca mance manco manda mandi mando " +
    "manga mangi mango mania manie manif manit manja manna manon manti manto " +
    "manus manzo mappa mappe marca marce marci marco marea maree maren mario " +
    "marmi marmo marsi marta marzo masca maseo masha massa masse massi masso " +
    "matai match mater maths matta matte matti matto matur maury mazon mazza " +
    "mazze mazzi mazzo mbito mbocc mbres mbria mbuco means meato mecca medeo " +
    "media medie medio megan melan melee melia melie melio mells melma memes " +
    "menir menos mensa mense menta mente menti mento merai merce merci merda " +
    "merde merge merit merlo merti messa messe messi messo meste mesto metal " +
    "meteo metri metro metta mette metti metto mezci mezza mezze mezzi mezzo " +
    "miamo miata micce micci miche micio micro midio miele miete migra migro " +
    "miles mileu milia milio milit mille milza mimar minem miner minet minor " +
    "minta miope miopi mirko mirne mirra mirto mista miste misti misto mitad " +
    "mitra mixer mleto mmaus mmerd mmett mmira mmiro mmuni mnium mochi modei " +
    "model modem modeo modio modos modus moent mogli mogna moine moire moked " +
    "molla molle molli mollo molta molte molti molto momen mommy monco mondi " +
    "mondo money monta monte monti monto mooka morbo morda morde mordi mores " +
    "moria morin morio morir morna morsa morse morsi morso morta morte morti " +
    "morto mosca mosce mosci mossa mosse mossi mosso mosto mostr motel motta " +
    "motti motto mount mouse moves movie mozza mozzo mpact mpara mpari mparo " +
    "mpero mpiet mpiga mpire mpoli mrkva mucca muffa muffe mujer multa multe " +
    "multi mundi mundo munto muoia muoio muore muori muort muova muove muovi " +
    "muovo murga muros musei museo music mutar muter mutua mutui mutuo muzej " +
    "mware mymap mysky nacio nafta naggi nagni naive nakin nammo nanas nanda " +
    "nanna nanne naomi narra narro nasca nasce nasci nasco nassa nassi natia " +
    "natio naura nausa nausg navig nazio ncase nchez nchor ncien ncino ncnte " +
    "ncome ncona ncora ncore ncubi ncubo ndaco ndale ndamo ndare ndata ndate " +
    "ndati ndava ndavo nders ndhra ndian ndias ndica ndice ndici ndies ndine " +
    "nding ndini ndios ndire nditi ndito ndizi ndoor ndrae ndrai ndrea ndrei " +
    "ndrej ndreo ndrew ndrey ndria ndrii ndriu neces necht necro negli negra " +
    "negri negro neide nelay nella nelle nelli nello nendo nenia nenie nergy " +
    "nerie nerno neroi nervi nervo nesco nescu nessi nesso nesti nesto netta " +
    "nette netti netto neuro nevee never nezda nfall nfame nfeld nferi nfidi " +
    "nfila nfilo nfine nform nfray ngaro ngela ngeli ngelo ngels ngera nghel " +
    "ngius ngkor nglia nglis ngola ngoli ngora ngoul ngrao ngres ngrid ngrum " +
    "nhalt niamo nical nicef niche nicht nidos niene nient niero night nigra " +
    "nikon nimal nimas ninfa ninfe ninja ninna ninne nione nioni nions niper " +
    "nipol nippo niqlo nique nirmi nisba nisce nisci nited nitre nivea nizia " +
    "nizio njetu nkano nkara nlabs nland nline nnali nnamo nnego nnese nnita " +
    "nnoto nnual nnuii nnuso nobel nobii nobis nodes noise nokia nolfi nolte " +
    "nomao nomea nomen nomin nonce nonch nonna nonne nonni nonno noooo norma " +
    "norme normi notai noter notes notte notti nouvo novel novit novus nozze " +
    "nrato nreal nrica nrico nsane nsani nsare nside nsiei nsoff nsson nster " +
    "nswer ntani ntent ntera ntere nteri nterk ntert ntesa ntica ntico ntlte " +
    "ntona ntoni ntony ntrai ntrod ntrst ntuii ntuos ntyre nudge nudit nulla " +
    "nulle nulli nullo numer nuoce nuora nuota nuoto nuova nuove nuovi nuovo " +
    "nutra nutre nutri nutro nutti nvano nvasi nvece nvita nvito nvoca nyder " +
    "nylon nyway nzago nzell nzich nzini nzisi nzola oabro oader oagli oasio " +
    "oates oatti oback obagi obain obald obane obank obart obben obbes obbia " +
    "obbie obbik obbio obbit oberg obert obesa obesi obeso obeya obias obiet " +
    "obile obili oblas obley oblii oblin oblio obner obold obolo obont oboso " +
    "obota oboto obots obras obria obruk obson oburg obuzi ocale ocali ocane " +
    "ocate occhi occia occup ocean ocene ocher ochte ocial ociet ocket ockey " +
    "ockin ockol oculo odama odano odard odari odaro oddio oddit odega odena " +
    "odere oderi odern odesi odest odger odham odica odice odici odiea odier " +
    "odile odina oding odini odino odium odney odoli odoma odono odora odore " +
    "odori odrum odula odule oduli odulo oduti odwin oeeui oeing oelho oelle " +
    "oelum oenna oenta oepli oesia oesie oethe oetry offee offel offia offio " +
    "offra offre offri offro ofoio often oftex ogana ogane ogaro ogart ogele " +
    "ogers oggia oggio ogica ogico ogita ogito ogive ogler oglia oglie oglio " +
    "ogues ogurt ogway ohann oheme ohhhh ohini ohinj ohith ohnny oholy ohson " +
    "oiani oiano oices oichi oielo oiero oight oimar oines oioso oipet ojack " +
    "ojava ojica ojmir ojoba okhla okker okola oksso oktua olace olana oland " +
    "olano olare olari oldat oldem olden older oldin oledo oleil olere oleri " +
    "olete oleva olevi olevo oleyn olfer olice olicy olido olina oline olise " +
    "olita olite oliti olito oliva olive olivi olivo olker olkin olkov ollar " +
    "olles olley ollia ollio ollon ollor ollov ollow olmes olnya oloff olomo " +
    "olona olong oloni olont olony olore olori oloro olors olosa oloso olski " +
    "olson olton oltre oltri olume oluto olvay olzio omaba omack omade omadi " +
    "omads omain omali omana omane omani omano omany omasi omaso ombat ombay " +
    "omber ombes ombie ombra ombre omecq omega omena omeno oment omeri omero " +
    "omert ometa omici omics omila omina omine oming omini omino omito omizi " +
    "ommen ommer ommes ommie ommon omney omnia omoda omodo omohn omolo omone " +
    "omore ompab ompas ompei ompeo omple ompra ompro omsey omune omuni onaca " +
    "onaci onaco onald onale onani onano onare onata onate onati onato onchi " +
    "oncho oncia ondat onday onder ondha ondon ondor ondov ondra ondry onely " +
    "onere oneri onero onest onete onfsl onger onghi ongia ongol ongue onham " +
    "onhap onica onico oniek onien onini onino onion oniti onizi onkey onley " +
    "onlia onlus onner onnet onnie onnio onnor onomo onomy onora onore onori " +
    "onoro onrad onroe onsip onsob onson ontag ontes ontra ontri ontro onway " +
    "onwww onzas onzio onzon ooden oodle oodoo oogla oogle ookie oomba oomis " +
    "oomla oomro oomua ooney ooper oorda oorno oorso oothe oover oovit opaca " +
    "opaco opali opera opere operi opero ophie oping opoli opolo opona oppea " +
    "opper oppia oppie oppio oppis opplr oppor oppue oprio opski optai opter " +
    "orafo orale orali orami orang orani orano orari orata orate orato oraya " +
    "orazd orbes orbis orbyn orces orche orchi orcia ordai ordan orden order " +
    "ordic ordin ordoi ordon orean oreca orena oreni oreno orenz oresi orest " +
    "oresu oreto orfea orfei orfeo organ orger orges orgex orghi orgia orgue " +
    "orian orica orice orien orina orini orino orire oritz oriva orker orkin " +
    "orlds ormac ormai ormal orman ormer ormez ormia ormio ormul ormuz ornai " +
    "ornby orneo orner ornet orodi orona orone oroni oroom oroty orpus orque " +
    "orrai orral orrei orrer orres orrie orris orror ortai ortal orteo orter " +
    "ortes ortex ortis orton ortus orure orvus osaic osano osare osati osato " +
    "osava osavi osavo oscar osche oschi oscoe oscow oseki oseph oserm osers " +
    "osher oshik oshua osiah osimi osimo osina osini osita oskov oskva osmio " +
    "osmos osnia osone osoni osovo ospir ospit osque ossae ossea ossee osseo " +
    "osses osset ossia ossil ossip ostar ostei ostel osten oster ostie ostin " +
    "oston ostra ostre ostri ostro ostru ostui osuke oszef otaio otaku otale " +
    "otare otari otary otate otato otavo otcom otels otere oteri otero otete " +
    "oteti oteva otevi otevo otham othar other othko othma otice otion otito " +
    "otivi otivo otler otlin otolo otone otori otoro otors otown otrai otrei " +
    "ottai otter ottom otton ottor ottos ouble ouchi oudon oudou oufan ougat " +
    "ouisa ouise ouman ounds ounes ounge ounty ouono oupon ource ourke ourne " +
    "ourse ousef ousie ousif oussa ousse outer outhi outro ouute ouvel ouvre " +
    "ovage ovaie ovale ovali ovana ovane ovara ovaro ovary ovata ovati oveja " +
    "ovela ovell ovely ovena overa overe overi overo overs overt ovest ovete " +
    "oveva ovevi ovevo ovian ovice ovida oviet ovigo ovile ovili ovina ovine " +
    "oving ovini ovink ovisa ovoli ovoni ovrai ovrei ovuli ovulo ovuto ovvia " +
    "ovvie ovvio oward owboy owder owell owers owest owgeb owler owles owman " +
    "owned owner ownes owney owran owser oyale oyata oyota oyote oypad ozaic " +
    "ozano ozart ozito ozono ozzao paale pacca pacci pacco pacee pacer pacey " +
    "pache padre padri paese paesi pagar pages paggi paghi pagna paini palco " +
    "paleo palio palla palle palma palme palmi palmo palpo palta panca pance " +
    "panda panel panic panna panne panni panno panta pants paola paoli paper " +
    "papli pappa pappe parap parca parco pardi paree pareo parer paria parie " +
    "parit parka parks parla parle parli parlo parma parro parsa parso parta " +
    "parte parti parto party parve pasci passa passe passi passo pasta paste " +
    "pasti pasto patch pater patha patio patir patri patta patti patto paura " +
    "paure pausa pause pavia pazia pazio pazza pazze pazzi pazzo pcita pdate " +
    "peace peaks pears pecca pecch pecie pedal peedy peers pegni pegno pelle " +
    "pelli pello penda pende pendi pener pengo penna penne pensa pensi penso " +
    "penta pente penti pento penur penzo peplo peppa pepys peque perae perch " +
    "perci perda perde perdi perdo perhc peria perir perla perle perma perni " +
    "perno perol persa perse persi perso perta perte perti perto pesca pesce " +
    "pesci pesco peser pesos pesso pesta peste pesti pesto petta petto pezia " +
    "pezza pezze pezzi pezzo phane phase phero phone photo physe piace piaci " +
    "piaga piana piane piani piano piazz picca picci picco piche picit pider " +
    "piede piedi piega piego piena piene pieni pieno pieve piezz pigna pigne " +
    "pigra pigre pigri pigro pilot pimpa pinal pinch pinea pingi pingo pinna " +
    "pinne pinta pinte pinti pinza pinze pioli piomb pione piova piove pipia " +
    "pippa pippe pippi piral pires pirit pirla pirlo pisci piske pista piste " +
    "pitch piuma piume pivot pixel pizza pizze pizzi pizzo placa place placo " +
    "plaid plana plans plate playa plaza plebe pleen plend plice plici plico " +
    "pliis pliss plume pluri pnosi poche pochi pocoo podio poema poemi poeta " +
    "poeti pogea pogeo poggi poich point poker polca polis polit polli pollo " +
    "polpa polpe polpi polpo polsi polso pompa pompe ponev ponga pongo ponno " +
    "ponte ponti poppa poque porca porci porco porge porgi porgo poria porla " +
    "porle pormi porno porre porse porsi porta porte porti porto ports porvi " +
    "possa posse posso posta poste posti posto posts potei poter potra potro " +
    "potti pouch pound pover povri power pozza pozze pozzi pozzo ppall ppare " +
    "ppdia ppela ppena pperl ppert ppesa ppido ppino ppure praga prati prato " +
    "pread preda prede prega pregi prego preli prelo preme premi premo prena " +
    "presa prese presi preso press prest prete preti preun previ prezi prica " +
    "price prile prima prime primi primo princ pring print prire prite priti " +
    "pritz priva prive privi privo prizi proda prode prodi progr proib prole " +
    "promo prone proni prono pronu proof prosa prose prota proto protr proud " +
    "prova prove provi provo prude psico psych psyco ptano ptima ption pucia " +
    "pugna pugni pugno pulce pulci pulsa pulse pulsi punge punja punse punta " +
    "punte punti punto purch purea purga purge purgo purit pussy putty puzza " +
    "puzze puzzi puzzo pwork pxdue qualc quale quali quand quano quant quare " +
    "quark quart quasi quass quati queen queer quell query quesi quest queta " +
    "quila quile quill quino quipe quire quirk quity qundo quota quote quoti " +
    "qurra qusta rabal rabby rabia rabos racce racci racco racer racey racia " +
    "racle ractl radam radar raden radeo rader radio radon raele raevo rafat " +
    "raffa rafft rafts ragal ragan raggi raggo raghi ragni ragno ragon ragot " +
    "raham raian raies rainz raken raldo rally ramai ramma rammi rammy rampa " +
    "rampe rampi ranca rance ranch ranci ranck ranco randa rande randi rando " +
    "randt ranet range rango rania ranio rankl ranko ranne ranno ransi ranta " +
    "ranti rantz ranza ranzl ranzo raper rapir rappa rario rarit rarsi rasal " +
    "rasca raser rasmo rasne rasoi rassa rasse rassi rasso rasta ratel ratic " +
    "ratio ratis ratta ratte ratti ratto ratus rauca rauco raujo rault raumi " +
    "ravas ravda ravel raver ravin ravis ravit raxis rayon razia razie razio " +
    "razza razze razzi razzo rbana rbane rbani rbano rbene rbera rbers rbino " +
    "rbita rbore rcade rcana rchie rcito rcole rcore rctic rdaaa rdati rdent " +
    "rdine rdini rdino rdita rdito rdjan rdono rdore reach ready reaer reaks " +
    "reale reali realt reame reami reams reamy reare reata reate reath reati " +
    "reato reaty rebbe rebbi rebus recai recap recen rechi recht recia redda " +
    "reddi reddo reddy reder redia redit reeks reene reens reeve reeze regal " +
    "regar reger regga regge reggo reghi regia regim regio regna regni regno " +
    "regon regor rehab reich rejas rejci rejus relax relay relaz releg rella " +
    "rello remap remel remer remio remix renae renda rende rendi rendo rends " +
    "rendt rener rengo renna renne renon renta renti rento rentr rents renza " +
    "renzi repax repet repit reply resce resci resco resda reset resno respi " +
    "respo ressa resse resso resta reste resti resto retna reton retro retta " +
    "rette retti retto retty reuil revas rever reves revit revor rexit rexpo " +
    "rezza rezzi rezzo rfano rfini rgana rgani rgano rgine rgone rgosu rguto " +
    "rhead riale rials rialz riamo riana riane riani riano riapo ribad ricas " +
    "ricca ricce ricci ricco ricev richi ricky ricll ridar ridas riday ridda " +
    "rider ridge ridia rieco rieda riede riege rieht riela riely riemp riend " +
    "riese riesi riete rifar riffo rigen riggs righe right rigia rigin rigio " +
    "rigir rigny rigor rigun riket rilev rillo rilly rimea rimer rimes rimia " +
    "rimus rince rinit rinks rinni rioli riolo rione rioni riony riore riori " +
    "rioso ripet ripit riplo ripos rippa rippi ripta ripte risal risas risci " +
    "risco risen risma rismo rison rissa risse rissy rista riste risto risul " +
    "riten riter ritir ritmi ritmo riton ritta ritte ritti ritto riuli riusc " +
    "riusi riuso rivel river rizza rizzi rizzo rkham rkiye rlano rlare rmaco " +
    "rmada rmand rmani rmata rmate rmati rmato rmeno rmete rmini rmisi rmita " +
    "rmour rnaud rnest rnett rnman rnold roane roati roato robba robot robus " +
    "rocca rocce rocco roche rochi rocio rociv rocks rococ rofei rofeo rofit " +
    "rofts roghi rogna rogne roica roici roika roina roisi rojan roken roldo " +
    "rolla rollo rolls rombi rombo romod rompa rompe rompi rompo ronca ronde " +
    "rondi rondt rones ronia ronos ronta ronte ronti ronto ronza ronzo rooke " +
    "rooks roots roper ropes ropez roppa roppe roppi roppo rosby rosea rosee " +
    "rosei roseo roses rospi rospo rossa rosse rossi rosso rotol roton rotta " +
    "rotte rotti rotto rotzu rouge rough round roups roust route rovai rover " +
    "rovin rowne royal rozac rozen rozza rozze rozzi rozzo rphan rpina rpino " +
    "rpska rquez rrani rrare rrata rrati rredi rredo rrico rrigo rritu rriva " +
    "rrivi rrivo rrore rrori rsene rsida rsina rsini rsino rsola rstel rsula " +
    "rtano rtaud rtega rtesc rthur rtica rtico rtist rtner rtobb rtuny rturo " +
    "rtusi rtuso rubai ruber rubli rublo rucco ruces ruche rucia rucio rucis " +
    "rudos ruela ruffa rugae rugby ruger ruges rughe rughi rugna ruido ruine " +
    "ruise rulli rullo ruman rumbo rummm rumor runch rundo runei runel runet " +
    "runig ruoli ruolo ruota ruote ruoti rupal rupia ruppe ruppi ruppo ruppy " +
    "rusca rusoe ruspa ruspe russa russe russi russo rusts rutch rutta rutti " +
    "rutto rvine rwell ryant rytek sabel sacca sacco sacra sacre sacri sacro " +
    "sagge saggi saghe sagne sagra sagre saias saidi saint salda salde saldi " +
    "saldo sales salga salgo salii salir salis salma salmi salmo salpa salsa " +
    "salse salta salti salto salut salva salve salvi salvo sando sanit sanno " +
    "santa sante santi santo saper sapev sappi sarai saran sarda sardi sardo " +
    "sarei sarla sarlo sarta sarte sarti sarto sassi sasso satto sauce sauer " +
    "sauna saune sauri savia savio savvy sazia sazie sazio sbafo sbaji sbarb " +
    "sbarr sbavi sbavo sbuca sbuco scada scade scadr scafi scafo scala scald " +
    "scale scali scalo scani scano scans scape scapp scari scati scatt scava " +
    "scavi scavo scema sceme scemi scemo scena scend scene scere scesa scese " +
    "scesi sceso schei scher schia scien scire scita scite sciti scito scivo " +
    "sclam scocc scoli scolo scona scono scont scool scoop scopa scope scopi " +
    "scopo scopr scord score scort scout scova scovo scrub scudi scudo scula " +
    "scura scure scuri scuro scusa scuse scusi scuso sdrai secca secco secdq " +
    "sedia sedie sedua seggi seghe segna segni segno segua segue segui seguo " +
    "selem sella seltz selva selve sembr sempe sempi sempr senno senor sense " +
    "sensi senso sensu senta sente senti sento senza seppe seppi seran serba " +
    "serbi serbo serei sergo seria serie serif serio serpe serra serre serto " +
    "serum serva serve servi servo sessa sessi sesso sesta sesto sesur setta " +
    "sette setti setto setup seudo seven sevoi sfama sfamo sfata sfera sfere " +
    "sferr sfida sfide sfidi sfido sfiei sfiga sfila sfili sfilo sfnno sfoca " +
    "sfoci sfoga sfogo sfori sforz sfott sfugg sfuma sfusi sfuso sgard sglie " +
    "sgran shake shale shall shame shant shape share sharq sheet shelf shell " +
    "sheol shhhh shift shirt shley shoah shock shoes shoot shops shore short " +
    "shots shout shraf shtml shton siago siail siamo siano siate sicch siche " +
    "sicob sicom sidro sieda siede siedi siedo sieno siepe siepi siero siete " +
    "sigla sigle siglo sigma signi signo sigur silos simil simov simpa sinch " +
    "sinht sinti sinuo siodo sione sioni siore siori sipap siris sisma sismi " +
    "siste situa situi skate skeet skifo skill skira skype sland slang slash " +
    "slava slavi sleep slega slice slide sloga slope slows slums slurp smael " +
    "smail small smart smile smini smise smisi smoke snack sneak sniff snoda " +
    "snodi snodo snort snuff soave sober sobre sobri soche socia socie socio " +
    "sodio soffi sogna sogni sogno sokol solai solca solco soldi soldo solea " +
    "soles solfa solis somma somme sommi sommo sonar sonda sonde sonni sonno " +
    "sonzo sopra sorda sorde sordi sordo sorfa sorga sorge sorgo sorio sorri " +
    "sorry sorse sorsi sorso sorta sorte sorti sorto sosia sosta soste sotta " +
    "sotto sound souri south sovra sozza sozzo space spada spade spago spala " +
    "spana spara spari sparo spazi spazz speak speed spejo spell spera speri " +
    "spero spesa spese spesi speso spett spezz spice spick spieg spiga spill " +
    "spina spine spira spire spiro spita spite spiti splat split spola spone " +
    "sponi spore sport sposa spose sposi sposo spost spoti spray spree spris " +
    "spuma spuri sputa sputi sputo sqday squat squot srael ssago ssari sseni " +
    "sseno ssere sseri ssets ssidi ssimi ssiom ssiri ssisi ssita sslin ssola " +
    "ssopo ssumi stacc stack stadi staff stage stana stand stani stano stant " +
    "stare stars start stasi stata state stati stato stava stavi stavo steak " +
    "steel steko steli stelo steps stera steri stero sterz stesa stese stesi " +
    "steso stica stick stico stikl stila stile stili still stima stime stimi " +
    "stimo stipa stira stiro stiss stiva stive stivo stock stona stone stono " +
    "store story strae streg strem stria strid strip strof strut sttit studi " +
    "study stufa stufi stufo stuni stupi stura style suant suaza subir succe " +
    "succo sucks sudor sugar sughi sugli suini suino suite sulla sulle sullo " +
    "sulpc sulto summa sunna sunto suola suole suolo suona suoni suono suora " +
    "suore super supra surfa surge sushi suwww svago svela sveli svelo svito " +
    "svolt sweet swing swipe sycho sylon synth sysop tabia table tacca tacce " +
    "tacco tacer tacia tadio tages tagga taggo tagli tagno taion taken takes " +
    "talco tales taley talia talib talie talin talke talla tallo talpa talpe " +
    "tammi tampa tanca tanco tancu tando tanfo tange tango tanis tanno tanta " +
    "tante tanti tanto tanza tanze tapas tapis tappa tappe tappi tappo tapum " +
    "tarci tarck tarda tarde tardi tardo targa tarib tarlo tarra tasca tassa " +
    "tasse tassi tasso tasti tasto tates tatic tatto tatua tawaf tayin tazza " +
    "tazze tcere teams tease teato teaua teche tecno tecum tefan tefen tehli " +
    "teins tekno telai telco telef telex telio tella telle tello telly temle " +
    "temma tempi templ tempo temps tenda tende tendi tendo teneo tener tenga " +
    "tengo tenia tenne tenni tenta tenti tento tenue tenui tenza tepee teper " +
    "terci terei terga tergo terlo terme termo terna terno terra terre terso " +
    "terun terza terze terzi terzo tessa tesse tesso testa teste testi testo " +
    "tetra tetre tetri tetro tetta tette tetti tetto teven tevia tevie texts " +
    "tgcom tgini tgone thaca thena theos there thers these thing think tiamo " +
    "ticom tidal tiene tieni tient tifel tiger tigna tigre tigri tiket tiles " +
    "tilit tills timer times timor tinga tinge tingi tinta tinte tinti tinto " +
    "tione tiopi tipli tirai tirar tirer tiria title tival tizia tizio tkins " +
    "tnale toale toast tobey tocca tocco today toffa toghe togli toile token " +
    "tokes tolga tolgo tolse tolsi tolta tolte tolti tolto tomba tombe tomic " +
    "tonda tondi tondo toner tones tonfo tonic tonni tonno tonto tools topia " +
    "topic topoi topos toppa toppo torba torca torce torda tordi toret toria " +
    "torie torma torme tormi tormo torna torni torno toros torre torri torsi " +
    "torso torta torte torti torto torva torve torvi torvo tosco tosse tosta " +
    "toste tosti tosto total totem touch tough tourn towns tozze tozzi tozzo " +
    "track trada trade trage tragi trail train trait traka trall trama trame " +
    "tramo trana trand trane trano trans trapn trarr trash trati trato tratt " +
    "trave travi tream treep treet trega trema treme tremo trend treni treno " +
    "trent tress triad trial tribu trike tring tripe trita trite triti trito " +
    "trmol troia troie troke troll trono tropo trota trote trova trovi trovo " +
    "truce truck trump trust truth ttack ttari ttati ttava ttavo ttesa ttica " +
    "ttico ttila ttima ttime ttimo ttito ttiva ttivo ttone ttore ttori tuart " +
    "tudes tudia tudio tuffa tuffi tuffo tulle tumpo tuned tunes tuona tuoni " +
    "tuono tupid tupir tuple tuppo tural turba turbe turbi turbo turca turco " +
    "turla turni turno turpe turpi tutor tutta tutte tutti tutto tuvan tweed " +
    "tweet twice twigs twist twood tyles tzeni uaaaa uadio uadra uadre uadri " +
    "uadro uagli uagua ualdo ualit uanda uando uanjo uanne uanta uante uanti " +
    "uanto uarda uardi uardo uareg uarez uarin uarni uarta uarte uarto uartz " +
    "uarzi uarzo uasar uasti uatto uawei ubana ubano ubare ubata ubate ubava " +
    "ubavo ubber ubbia ubbio ubble ubici ubick ubini ubino ubita ubite ubiti " +
    "ubito ublai ublic ublin uborg ubrik ubrin ubris ubway ubwna ucale ucane " +
    "ucani ucano ucato uccel ucchi uccia uccio ucens uchan ucian ucida ucide " +
    "ucina ucine ucini ucino ucite ucius ucker ucket uckup ucleo ucola ucron " +
    "ucson udace udato udavo udawi uddha udens udget udima udine udire udite " +
    "udith uditi udito udolf udore udrey udrio udson uduro udwig uebec ueblo " +
    "ueens uegli ueijo uelfi uelfo uella uelle uelli uello uenos uente uerra " +
    "uerre uerte uerto uerty uesta ueste uesti uesto uetta uetti ueuua ueyen " +
    "uezon ufala ufale ufata uffer uffet uffin uffon ufini ufiya ufour ugabe " +
    "ugace ugani ugano ugaro ugazi ugene ugent ugeri uggia ugher ughes ugias " +
    "ugier ugine ugini ugino uglia uglio ugnai ugnot ugual uguri uguro ugust " +
    "uhari uhner uhoor uidad uides uidit uiete uilio uilla uindi uinea uinoa " +
    "uinta uinto uiper uites uixot ujhfs ujica ukhoi uksas uktar ulcis ulcro " +
    "ulder ulent ulero ulese ulesi ulian ulija ulimi ulino ulire ulite uliti " +
    "ulito ulius uliva ulivi ulivo ullah ullen uller ullet ullio ullit ulteq " +
    "ultra ulula ulvad ulvia ulvio umami umana umane umani umano umans umanx " +
    "umare umavo umbai umber umble umblr umbra umbre umbri umbro umeri umero " +
    "umici umida umide umidi umido umile umili umilt uming umini umito ummer " +
    "ummit ummus umner umola umont umore umori umors umper umpur unafa unale " +
    "uname unare unari unbar uncan unday undee undem under undra unduz unedi " +
    "ungas unger unghe unghi ungie ungiu ungla ungry unham unica unich unici " +
    "unico unier unimi union unior unire unisi unita unite uniti unito units " +
    "univa unive unjab unker unnan unnar unnel unner unnia unnnk unnon unque " +
    "unset unter unway unyan unzia unzio uochi uoghi uolly uomoe uongo uozzi " +
    "upera upero upert upfer upica upido upini upply uqbal urace urale urali " +
    "urand urano urare uraro urata urati urato uraxi urban urbex urcas urcet " +
    "urchi urcia urcio urden urder ureau urena ureus urfer urger urgia urham " +
    "urher urico uriev urigo urina urine uring urini urity urker urkle urlai " +
    "urlan urler urlon urner uroma urone urono uropa urope urora urore urphy " +
    "urple urpom urray urrey urris ursas ursia urska urski urter urtis urtle " +
    "urton urvey urzel urzio usali usalo usana usani usano usare usaro usata " +
    "usate usati usato usava usavi usavo uscas uscia uscii uscio uscir useet " +
    "users useum useun ushra usica usici usino usion usith usitu uskas uskin " +
    "usone ussel ussia ussie ussin ustav usten uster ustin ustle ustom uston " +
    "ustos ustro usual usura usure utaia utano utant utela utell utera utero " +
    "uthan uther uthor utile utili utina utino utitu utler utnam utoar utolo " +
    "utoma utore utori utput utsal utter utton utuli utumn utura uture uturi " +
    "uturo uuren uvant uvesi uvola uvole uvvia uwait uweid uxley uxury uyana " +
    "uyaup uyghe uzman uzuki uzzle vabbe vacca vache vacua vacue vacui vacuo " +
    "vaffa vaghe vaghi vagli valer valga valgo valle valli vallo valor valsa " +
    "valse valso value valut valve vammi vampa vampe vanga vanit vanno vanta " +
    "vanti vanto vanzi vanzo vapor varca varco varia varie vario vasca vasta " +
    "vaste vasti vasto vatar veder vegan vello velyn venco venda vende vendi " +
    "vendo veneu venga vengo venia venir venne venni venti vento vents venue " +
    "verba verbi verbo verde verdi verie veris verit verki verle verme vermi " +
    "verna veroe verra verro versa versi verso verte verve vervi verza verze " +
    "vespa vespe vessa vesse vessi vesta veste vesti vesto vetan vetik vetri " +
    "vetro vetta vette vetti vevia vezda vezia vezzi vezzo vgeny vgust viale " +
    "viali viamo viano viare vibra vicer vicie video vidia vidic vidio vidse " +
    "viedo viene vieni viere vieta vieti views vigna vigne viino villa ville " +
    "vimeo vimez vinca vince vinci vinco vinix vinos vinse vinsi vinta vinte " +
    "vinti vinto vinyl viola viole violi viral virtu virus visit vispa vispe " +
    "vispo visse vissi vista viste visti visto vitae vitai vital vitam viter " +
    "vitro vitto viver vizia vizio vodka voice voler volga volge volgo volio " +
    "volle volli volpe volpi volse volsi volta volte volti volto volve volvo " +
    "vomit voque vorio vorra vostr voter vremo vrete vucca vulva vuole vuota " +
    "vuote vuoti vuoto vvero vviet vviso vviva wadwo wagon waken wanda wange " +
    "wanna wards wartz washi watch water webbe weeks weets welve wente wenty " +
    "weren whale whead wheel where white whois whole width windy wired witch " +
    "witty woman women works world worst write wrong wuxia wxrrk xezov xford " +
    "xilia ximia xitus xodus xpert xport xpose xpost xshuu xsona xxxxx xygen " +
    "yacht yahoo yakko yalla yanna yborg ybrid yclee ydney ydrae years yelet " +
    "yemen yenge yerba yeres ygmut yhavn yklon ykwer yleta ylvia ylvie ymbol " +
    "yodor young youtu yoyoj yphon yping ypora yprus yrano yrdal yrell yrian " +
    "yrion yriza yrtis yrtle yrton ystem yster ytali ythos yuara yushu yword " +
    "zacco zaini zaino zampa zampe zanna zanne zante zappa zappo zaret zarny " +
    "zassu zawad zcorp zdore zebra zebre zecca zenit zeppa zeppe zeppi zeppo " +
    "zilla zimut zinco zione zioni zioso zitta zitte zitti zitto zizze zodan " +
    "zolfo zolla zolle zombi zomma zonzo zoppa zoppi zoppo zozza zozze zozzi " +
    "zquez zsuna zteca zuava zucca zuffa zuffe zuppa zuppe zzard zzaro zzoni "
  )
    .trim()
    .split(" "),
);
